version: '3'

services:
  payment-gateway-api:
    image: payment-gateway-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    build:
      context: .
      dockerfile: deploy/Docker/Dockerfile
      args:
        RELEASE_VERSION: ${RELEASE_VERSION}
    ports:
      - 9501:9501
    depends_on: 
      - payment-gateway-database
  unit-tests:
    image: payment-gateway-api-unit-tests
    build:
      context: .
      dockerfile: deploy/Docker/Dockerfile
      target: unit-tests
      args:
        RELEASE_VERSION: ${RELEASE_VERSION}
  integration-tests:
    image: payment-gateway-api-integration-tests
    build:
      context: .
      dockerfile: deploy/Docker/Dockerfile
      target: integration-tests
      args:
        RELEASE_VERSION: ${RELEASE_VERSION}
  payment-gateway-database:
    image: postgres:14.4
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 5s
      retries: 5
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=docker
      - APP_DB_PASS=docker
      - APP_DB_NAME=payment_gateway
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432