version: '3'

services:
  database:
    image: postgres:14.4
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 5s
      retries: 5
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=docker
      - APP_DB_PASS=docker
      - APP_DB_NAME=payment_gateway
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432